export default {
  head: {
    title: 'Mobile World',
    htmlAttrs: {
      lang: 'en',
    },
    meta: [
      { charset: 'utf-8' },
      { 'http-equiv': 'X-UA-Compatible', content: 'IE=edge' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1, shrink-to-fit=no' },
      { name: 'keywords', content: 'HTML5 Template' },
      { name: 'description', content: 'Mobile World' },
      { name: 'author', content: 'p-themes' },
      { name: 'apple-mobile-web-app-title', content: 'Molla' },
      { name: 'application-name', content: 'Molla' },
      { name: 'msapplication-TileColor', content: '#cc9966' },
      { name: 'msapplication-config', content: '/assets/images/icons/browserconfig.xml' },
      { name: 'theme-color', content: '#ffffff' },
    ],
    link: [
      { rel: 'apple-touch-icon', sizes: '180x180', href: '/assets/images/icons/apple-touch-icon.png' },
      { rel: 'icon', type: 'image/png', sizes: '32x32', href: '/assets/images/icons/favicon-32x32.png' },
      { rel: 'icon', type: 'image/png', sizes: '16x16', href: '/assets/images/icons/favicon-16x16.png' },
      { rel: 'manifest', href: '/assets/images/icons/site.html' },
      { rel: 'mask-icon', href: '/assets/images/icons/safari-pinned-tab.svg', color: '#666666' },
      { rel: 'shortcut icon', href: '/assets/images/icons/favicon.ico' },
      { rel: 'stylesheet', href: '/assets/css/line-awesome.min.css' },
      // { rel: 'stylesheet', href: '/assets/css/font-awesome.min.css' },
      { rel: 'stylesheet', href: '/assets/css/bootstrap.min.css' },
      { rel: 'stylesheet', href: '/assets/css/plugins/magnific-popup/magnific-popup.css' },
      { rel: 'stylesheet', href: '/assets/css/plugins/owl-carousel/owl.carousel.css' },
      { rel: 'stylesheet', href: 'https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css' },
      // Add Google Fonts link for Roboto with Vietnamese subset
      { rel: 'stylesheet', href: 'https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap' },
      { rel: 'stylesheet', href: '/assets/css/M_Modification_index.css' },
      { rel: 'stylesheet', href: '/assets/css/style.css' },
      { rel: 'stylesheet', href: '/assets/css/skins/skin-demo-4.css' },
      { rel: 'stylesheet', href: '/assets/css/demos/demo-4.css' },
    ],
    script: [
      { src: '/assets/js/jquery.min.js', defer: true },
      { src: '/assets/js/jquery.plugin.min.js', defer: true },
      { src: '/assets/js/jquery.countdown.min.js', defer: true },
      { src: '/assets/js/owl.carousel.min.js', defer: true },
      { src: '/assets/js/bootstrap.bundle.min.js', defer: true },
      { src: '/assets/js/jquery.hoverIntent.min.js', defer: true },
      { src: '/assets/js/jquery.waypoints.min.js', defer: true },
      { src: '/assets/js/superfish.min.js', defer: true },
      { src: '/assets/js/bootstrap-input-spinner.js', defer: true },
      { src: '/assets/js/jquery.magnific-popup.min.js', defer: true },
      { src: '/assets/js/main.js', defer: true },
      { src: '/assets/js/demos/demo-4.js', defer: true },
      { src: '/assets/js/demos/price-range.js', defer: true },      
      { src: '/assets/js/nouislider.min.js', defer: true },
      { src: '/assets/js/wNumb.js', defer: true },
    ],
  },
  css: [
    '~/assets/css/main.css',
    'aos/dist/aos.css',
  ],
  plugins: [
    { src: '~/plugins/external-scripts.js', mode: 'client' },
    { src: '~/plugins/smooth-scroll.js', mode: 'client' },
    { src: '~/plugins/mdi.js', mode: 'client' },
  ],
  components: true,
  buildModules: ['@nuxtjs/eslint-module', '@nuxt/postcss8'],
  modules: [],
  build: {
    postcss: {
      plugins: {
        tailwindcss: {},
        autoprefixer: {},
      },
    },
  },
};